ALTER TABLE question
    MODIFY COLUMN `gmt_create` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
    MODIFY COLUMN `gmt_modified` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `user`
    MODIFY COLUMN `gmt_create` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
    MODIFY COLUMN `gmt_modified` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP;